### ISSUE TITLE
Estória de Usuário

### ISSUE THREAD

**Issue by projeto-aplicado** [projeto-aplicado/PointStore#1]
Identificador: E001
Complexidade: baixa
Prioridade: alta
Descrição:  Como cliente de negócio, gostaria de reunir informações sobre todos os pontos, dotes e milhas que possuo para que seja possível vende-las, troca-las ou comprá-las. 

Identificador: E002
Complexidade: alta
Prioridade: alta
Descrição:  Como cliente de negócio, gostaria de conversar com outros clientes, com o objetivo de facilitar a negociação dos valores.

Identificador: E003
Complexidade: média
Prioridade: alta
Descrição:  Como cliente de negócio, gostaria de poder filtrar as informações  por tipo, melhores preços, ou pelos usuários com maior quantidade de pontos, com o objetivo de reduzir o tempo de pesquisa.

**Comment by ericknilsen** [comment]
E001: vende-las, troca-las ou compar. (comprá-las)
E002: gostaria de um chat entre os usuários (gostaria de conversar com outros clientes)
