### ISSUE TITLE
TAP

### ISSUE THREAD

**Issue by Jafal** [projeto-aplicado/PointStore#2]
Definir os objetivos do projeto e utilizar o padrão S.M.A.R.T.  Acesse os links abaixo para leitura sobre esse padrão.

http://escritoriodeprojetos.com.br/objetivos-smart
http://www.psicologiafree.com/conselhos_praticos/como-definir-objetivos-ferramenta-smart-3/

Escopo: Descrever com mais detalhes. Veja o exemplo no modelo de TAP anexado.

Recomendo acesso ao anexo Iniciacao-Projeto e reescrever o TAP
[Iniciação-Projeto.pdf](https://github.com/projeto-aplicado/PointStore/files/477513/Iniciacao-Projeto.pdf)

**Comment by projeto-aplicado** [comment]
[TAP-FINALIZADO.docx](https://github.com/projeto-aplicado/PointStore/files/490574/TAP-FINALIZADO.docx)

**Comment by Juanvic** [comment]
[TAP-FINALIZADO e ATUALIZADO](https://github.com/projeto-aplicado/PointStore/files/642981/TAP-FINALIZADO.docx.docx)
