### ISSUE TITLE
EAP

### ISSUE THREAD

**Issue by Jafal** [projeto-aplicado/PointStore#3]
Não consigo identificar na EAP o que são entregas e subdivisão do trabalho. Acessar conteúdo anexo e refazer a EAP.
[Processo-Criar-EAP.pdf](https://github.com/projeto-aplicado/PointStore/files/477581/Processo-Criar-EAP.pdf)

**Comment by projeto-aplicado** [comment]
![eap_pa](https://cloud.githubusercontent.com/assets/21959483/18799866/75e064c6-81b0-11e6-9a76-b7886e0707dd.jpg)
